### ISSUE TITLE
CI: GHA doesn’t show test logs and outcomes

### ISSUE THREAD

**Issue by strogonoff** [ietf-tools/bibxml-service#307]
### Describe the issue

According to the logs, it appears as if everything starts and then shuts down.

The errors in log messages are likely not the cause. They are logged by DB layer, and are caught by calling code as required. It could be that tests may be executed in background, but we don’t see any output from them.

```
...
bibxml-service-test-db-1     | 
[2132](https://github.com/ietf-ribose/bibxml-service/actions/runs/3281919051/jobs/5404603862#step:3:2133)
bibxml-service-test-db-1     | PostgreSQL init process complete; ready for start up.
[2133](https://github.com/ietf-ribose/bibxml-service/actions/runs/3281919051/jobs/5404603862#step:3:2134)
bibxml-service-test-db-1     | 
[2134](https://github.com/ietf-ribose/bibxml-service/actions/runs/3281919051/jobs/5404603862#step:3:2135)
bibxml-service-test-db-1     | 2022-10-19 13:23:48.630 UTC [1] LOG:  starting PostgreSQL 14.2 (Debian 14.2-1.pgdg110+1) on x86_64-pc-linux-gnu, compiled by gcc (Debian 10.2.1-6) 10.2.1 20210110, 64-bit
[2135](https://github.com/ietf-ribose/bibxml-service/actions/runs/3281919051/jobs/5404603862#step:3:2136)
bibxml-service-test-db-1     | 2022-10-19 13:23:48.630 UTC [1] LOG:  listening on IPv4 address "0.0.0.0", port 5432
[2136](https://github.com/ietf-ribose/bibxml-service/actions/runs/3281919051/jobs/5404603862#step:3:2137)
bibxml-service-test-db-1     | 2022-10-19 13:23:48.630 UTC [1] LOG:  listening on IPv6 address "::", port 5432
[2137](https://github.com/ietf-ribose/bibxml-service/actions/runs/3281919051/jobs/5404603862#step:3:2138)
bibxml-service-test-db-1     | 2022-10-19 13:23:48.634 UTC [1] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
[2138](https://github.com/ietf-ribose/bibxml-service/actions/runs/3281919051/jobs/5404603862#step:3:2139)
bibxml-service-test-db-1     | 2022-10-19 13:23:48.638 UTC [65] LOG:  database system was shut down at 2022-10-19 13:23:48 UTC
[2139](https://github.com/ietf-ribose/bibxml-service/actions/runs/3281919051/jobs/5404603862#step:3:2140)
bibxml-service-test-db-1     | 2022-10-19 13:23:48.642 UTC [1] LOG:  database system is ready to accept connections
[2140](https://github.com/ietf-ribose/bibxml-service/actions/runs/3281919051/jobs/5404603862#step:3:2141)
bibxml-service-test-1        | Checking availability of test-db:5432
[2141](https://github.com/ietf-ribose/bibxml-service/actions/runs/3281919051/jobs/5404603862#step:3:2142)
bibxml-service-test-1        | Host test-db:5432 is now available!
[2142](https://github.com/ietf-ribose/bibxml-service/actions/runs/3281919051/jobs/5404603862#step:3:2143)
bibxml-service-test-1        | --------------------------------------------------------
[2143](https://github.com/ietf-ribose/bibxml-service/actions/runs/3281919051/jobs/5404603862#step:3:2144)
bibxml-service-test-1        | docker-compose-wait - Everything's fine, the application can now start!
[2144](https://github.com/ietf-ribose/bibxml-service/actions/runs/3281919051/jobs/5404603862#step:3:2145)
bibxml-service-test-1        | --------------------------------------------------------
[2145](https://github.com/ietf-ribose/bibxml-service/actions/runs/3281919051/jobs/5404603862#step:3:2146)
bibxml-service-test-db-1     | 2022-10-19 13:24:19.535 UTC [77] ERROR:  duplicate key value violates unique constraint "api_ref_data_ref_dataset_3182f6b6_uniq"
[2146](https://github.com/ietf-ribose/bibxml-service/actions/runs/3281919051/jobs/5404603862#step:3:2147)
bibxml-service-test-db-1     | 2022-10-19 13:24:19.535 UTC [77] DETAIL:  Key (ref, dataset)=(ref_01, test_dataset_01) already exists.
[2147](https://github.com/ietf-ribose/bibxml-service/actions/runs/3281919051/jobs/5404603862#step:3:2148)
bibxml-service-test-db-1     | 2022-10-19 13:24:19.535 UTC [77] STATEMENT:  INSERT INTO "api_ref_data" ("dataset", "ref", "body", "latest_date", "representations", "ref_id", "ref_type") VALUES ('test_dataset_01', 'ref_01', '{}', '2022-10-19'::date, '{}', '', '') RETURNING "api_ref_data"."id"
[2148](https://github.com/ietf-ribose/bibxml-service/actions/runs/3281919051/jobs/5404603862#step:3:2149)
bibxml-service-test-1 exited with code 1
[2149](https://github.com/ietf-ribose/bibxml-service/actions/runs/3281919051/jobs/5404603862#step:3:2150)
Aborting on container exit...
[2150](https://github.com/ietf-ribose/bibxml-service/actions/runs/3281919051/jobs/5404603862#step:3:2151)
Container bibxml-service-test-1  Stopping
[2151](https://github.com/ietf-ribose/bibxml-service/actions/runs/3281919051/jobs/5404603862#step:3:2152)
Container bibxml-service-test-1  Stopped
[2152](https://github.com/ietf-ribose/bibxml-service/actions/runs/3281919051/jobs/5404603862#step:3:2153)
Container bibxml-service-test-db-1  Stopping
[2153](https://github.com/ietf-ribose/bibxml-service/actions/runs/3281919051/jobs/5404603862#step:3:2154)
Container bibxml-service-test-redis-1  Stopping
[2154](https://github.com/ietf-ribose/bibxml-service/actions/runs/3281919051/jobs/5404603862#step:3:2155)
Container bibxml-service-test-db-1  Stopped
[2155](https://github.com/ietf-ribose/bibxml-service/actions/runs/3281919051/jobs/5404603862#step:3:2156)
Container bibxml-service-test-redis-1  Stopped
[2156](https://github.com/ietf-ribose/bibxml-service/actions/runs/3281919051/jobs/5404603862#step:3:2157)
Error: Process completed with exit code 1.
```

### Code of Conduct

- [X] I agree to follow the [IETF's Code of Conduct](https://github.com/ietf-tools/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by strogonoff** [comment]
Update: this is not such a heisenbug after all. Apparently, our CI test configuration is such that we store _actual_ test results in a file called `/test-artifacts/stderr.log` on host machine.

This file can be found by inspecting data loally, but does not seem to appear in CI output in GHA. Somehow this slipped through the cracks and was only found out now when build became red due to a single test failing and I couldn’t see why.

`stderr.log` contains actual log output such as:

```
...
    raise RefNotFoundError()
main.exceptions.RefNotFoundError: Item not found
.Failed to obtain or validate indexed bibliographic item when resolving xml2rfc path for I-D I-D.ietf-hip-rfc5201-is
Traceback (most recent call last):
  File "/code/bibxml/xml2rfc_adapters.py", line 217, in resolve
    indexed_bibitem = self.build_bibitem_from_refs(self.fetch_refs())
  File "/code/bibxml/xml2rfc_adapters.py", line 190, in fetch_refs
    return [sorted(
IndexError: list index out of range
Indexed bibliographic item found when resolving xml2rfc path for I-D I-D.ietf-hip-rfc5201-is lacks I-D version
Starting new HTTPS connection (1): datatracker.ietf.org:443
https://datatracker.ietf.org:443 "GET /api/v1/doc/document/draft-ietf-hip-rfc5201-is/?format=json HTTP/1.1" 404 None
Failed to fetch or validate latest draft from Datatracker when resolving xml2rfc bibxml3 path
Traceback (most recent call last):
  File "/code/bibxml/xml2rfc_adapters.py", line 237, in resolve
    dt_bibitem = get_internet_draft(
  File "/code/datatracker/internet_drafts.py", line 80, in get_internet_draft
    raise RefNotFoundError()
main.exceptions.RefNotFoundError: Item not found
...........Failed to hydrate related bibitem W3C, W3C PR-powder-grouping-20090604: Not found in indexed sources by docid
Failed to hydrate related bibitem W3C, W3C powder-errata: Not found in indexed sources by docid
..get_primary_docid(): unexpected number of primary docids found for [DocID(id='primary_id_value', type='type', primary=False, scope=None), DocID(id='id2', type='type2', primary=None, scope=None), DocID(id='id3', type='type3', primary=Non
e, scope='scope')]: 0
........Unexpected bibliographic item format: [{'id': 'RFC 4035', 'type': 'IETF', 'primary': True}, {'id': 'RFC4035', 'type': 'IETF', 'scope': 'anchor'}, {'id': '10.17487/RFC4035', 'type': 'DOI'}], 1 validation error for BibliographicItem
contributor -> 0 -> person -> name
  FullName.__init__() got an unexpected keyword argument 'initial' (type=type_error)
...........get_primary_docid(): unexpected number of primary docids found for [DocID(id='primary_id_value', type='type', primary=False, scope=None), DocID(id='id2', type='type2', primary=False, scope=None), DocID(id='id3', type='type3', p
rimary=False, scope='scope')]: 0
...
======================================================================
ERROR: test_ieee (xml2rfc_compat.tests.test_adapters.XML2RFCAdaptersTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/code/xml2rfc_compat/tests/test_adapters.py", line 103, in test_ieee
    bibitem = adapter.resolve()
  File "/code/xml2rfc_compat/adapters.py", line 89, in resolve
    self.resolved_item = self.build_bibitem_from_refs(refs)
  File "/code/xml2rfc_compat/adapters.py", line 217, in build_bibitem_from_refs
    composite_item, valid = compose_bibitem(refs, strict=True)
  File "/code/main/query_utils.py", line 71, in compose_bibitem
    bibitem, validation_errors = construct_bibitem(ref.body, strict)
  File "/code/bib_models/util.py", line 51, in construct_bibitem
    bibitem = BibliographicItem(**data)
  File "/usr/local/lib/python3.10/dist-packages/pydantic/main.py", line 341, in __init__
    raise validation_error
pydantic.error_wrappers.ValidationError: 4 validation errors for BibliographicItem
copyright -> 0 -> owner -> 0 -> abbreviation
  instance of GenericStringValue, tuple or dict expected (type=type_error.dataclass; class_name=GenericStringValue)
copyright -> 0 -> owner -> 0
  Person.__init__() got an unexpected keyword argument 'url' (type=type_error)
copyright -> from
  value is not a valid integer (type=type_error.integer)
copyright -> owner
  field required (type=value_error.missing)

----------------------------------------------------------------------
Ran 50 tests in 4.322s

FAILED (errors=1)
Destroying test database for alias 'default'...
```

We need to make this output more exposed in GHA.

(cc @ronaldtse and @kesara as an update on the test situation, cc @stefanomunarini)

**Comment by stefanomunarini** [comment]
PR #306 contains the fix to this issue

**Comment by strogonoff** [comment]
Let’s see if it works in the fork/PR before it’s merged😉On 19 Oct 2022, at 9:03 PM, Stefano ***@***.***> wrote:﻿
PR #306 contains the fix to this issue

**Comment by strogonoff** [comment]
It seems to be fixed. Messages show in container output locally and on GHA.

**Comment by strogonoff** [comment]
Thanks @stefanomunarini!
